# Generated by Django 3.2.8 on 2021-10-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211019_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': [('change_notes', 'Can change appointment')]},
        ),
    ]
