# Generated by Django 3.2.8 on 2021-10-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollquestion')),
            ],
        ),
    ]
