# Generated by Django 3.2.8 on 2021-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20211019_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
