# Generated by Django 3.2.8 on 2021-10-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_pollquestion_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='poll_question',
        ),
        migrations.DeleteModel(
            name='PollQuestion',
        ),
    ]
