# Generated by Django 3.2.8 on 2021-10-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20211019_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollAnswer',
        ),
    ]
