# Generated by Django 3.2.8 on 2021-10-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_delete_pollanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('question_type', models.IntegerField(blank=True, default=0)),
                ('question_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer', models.CharField(max_length=10)),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollquestion')),
            ],
        ),
    ]
