# Generated by Django 3.2.8 on 2021-10-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20211019_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
