# Generated by Django 3.2.8 on 2021-10-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20211019_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
