# Generated by Django 3.2.8 on 2021-10-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_pollquestion_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='poll_question',
        ),
        migrations.AddField(
            model_name='pollanswer',
            name='poll',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.poll'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='question_text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
