# Generated by Django 3.2.8 on 2021-10-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20211019_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='poll',
        ),
    ]
