# Generated by Django 3.2.8 on 2021-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_pollanswer_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='pollanswer',
            name='answer_id',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='pollanswer',
            name='answer_text',
            field=models.CharField(default='', max_length=10),
        ),
    ]
