# Generated by Django 3.2.8 on 2021-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20211019_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='question_type',
            field=models.IntegerField(blank=True, choices=[('own_asnwer', 'Свой ответ'), ('choices_answer', 'Вариант на выбор')], default=0),
        ),
    ]
