# Generated by Django 3.2.8 on 2021-10-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_pollquestion_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='poll',
        ),
        migrations.AddField(
            model_name='pollanswer',
            name='question_poll',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='question_type',
            field=models.IntegerField(blank=True, choices=[('own_asnwer', 'own_asnwer'), ('choices_answer', 'choices_answer')], default=0),
        ),
    ]
