# Generated by Django 3.2.8 on 2021-10-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20211019_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='question_type',
            field=models.IntegerField(blank=True, choices=[('own_asnwer', 'own_asnwer'), ('choices_answer', 'choices_answer')], default='own_asnwer'),
        ),
    ]
