# Generated by Django 3.2.8 on 2021-10-19 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_alter_pollquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='question_poll',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.pollquestion'),
        ),
    ]
