# Generated by Django 3.2.8 on 2021-10-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_pollanswer_question_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='question_poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.pollquestion'),
        ),
    ]
