# Generated by Django 3.2.8 on 2021-10-19 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_pollanswer_question_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='question_poll',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.pollquestion'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='question_text',
            field=models.CharField(max_length=250),
        ),
    ]
